FPO-156: Adds healthcheck validation
This is used for releases so is essential

diff --git a/.circleci/bin/smoketest b/.circleci/bin/smoketest
--- a/.circleci/bin/smoketest
+++ b/.circleci/bin/smoketest
@@ -27,6 +27,14 @@ if [[ "$STATUS_CODE" -ne 200 ]] ; then
   exit 1
 fi
 
+# Ensure it responds to a healthcheck
+STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "${URL}/healthcheck")
+
+if [[ "$STATUS_CODE" -ne 200 ]] ; then
+  echo "ERROR: Status code of $STATUS_CODE" >&2
+  exit 1
+fi
+
 # Ensure it responds with a 401 if credentials are missing
 STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "${URL}/fpo-code-search?q=grilled+cheese&digits=6")
 
