FPO-278: Explicitly handle failures

diff --git a/.circleci/bin/validatemodel b/.circleci/bin/validatemodel
--- a/.circleci/bin/validatemodel
+++ b/.circleci/bin/validatemodel
@@ -15,6 +15,11 @@ function check_validation() {
     echo "Model has already passed validation"
     exit 0
   fi
+
+  if aws s3 ls "s3://$MODEL_BUCKET_NAME/$VERSION_PREFIX/failed" 2>&1 | grep -q 'failed'; then
+    echo "Model has already failed validation"
+    exit 1
+  fi
 }
 
 function notify_slack() {
