BAU: Configure alternatives and install c++

diff --git a/.packer/provision b/.packer/provision
--- a/.packer/provision
+++ b/.packer/provision
@@ -12,6 +12,7 @@ sudo yum remove openssl-devel awscli -y
 sudo yum install -y \
   git               \
   gcc10             \
+  gcc10-c++         \
   make              \
   patch             \
   zlib-devel        \
@@ -39,11 +40,30 @@ eval "$(pyenv init -)"
 pyenv install "$PYTHON_VERSION"
 pyenv global "$PYTHON_VERSION"
 
-# Configure pyenv for login/non-login shells
 echo 'export PYENV_ROOT="$HOME/.pyenv"' >> "$HOME/.bashrc"
 echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> "$HOME/.bashrc"
 echo 'eval "$(pyenv init --path)"' >> "$HOME/.bashrc"
 echo 'eval "$(pyenv init -)"' >> "$HOME/.bash_profile"
+
+sudo alternatives --install /usr/bin/gcc gcc /usr/bin/gcc10-gcc 50
+sudo alternatives --install /usr/bin/g++ g++ /usr/bin/g++10 50
+sudo alternatives --set gcc /usr/bin/gcc10-gcc
+sudo alternatives --set g++ /usr/bin/g++10
+
+if ! command -v gcc10-gcc &>/dev/null; then
+  echo "Error: gcc10-gcc not found"
+  exit 1
+fi
+if ! command -v g++10 &>/dev/null; then
+  echo "Error: g++10 not found"
+  exit 1
+fi
+
+export CC=/usr/bin/gcc10-gcc
+export CXX=/usr/bin/g++10
+
+gcc --version
+g++ --version
 
 git clone "https://github.com/trade-tariff/${GIT_REPO}.git" --depth=1
 echo "$PYTHON_VERSION" > "$GIT_REPO/.python-version"
